### ISSUE TITLE
Debian 8.2 install: lsb_release is missing

### ISSUE THREAD

**Issue by priit** [benhoskings/babushka#332] opened 2015-11-02 16:02 UTC
Somehow debian 8.2 where missing lsb_release and initial (sh -c "`curl https://babushka.me/up`") babushka install failed with error: 

```
/root/.babushka/bootstrap/lib/babushka/popen.rb:21:in `exec': No such file or directory - lsb_release (Errno::ENOENT)
```

I followed: http://serverfault.com/questions/476485/do-some-debian-builds-not-have-lsb-release where it was suggested to install lsb-release package manually.

If you need help, I could investigate how to permanently create a patch to babushka to fix it, please let me know.

**Comment by schnittchen** [comment] 2016-01-16 16:36
I can confirm this issue.

**Comment by victorklos** [comment] 2016-09-08 12:40
This is caused by the fix for #329 btw

**Comment by benhoskings** [comment] 2017-02-28 11:37
Closing this for now; if it's still a problem on debian patches are welcome.

**Closed by benhoskings** 2017-02-28 11:37 UTC
